### ISSUE TITLE
missing method? "local_file_exists"

### ISSUE THREAD

**Issue by grafikchaos** [augustash/capistrano-ash#10]
I was perusing the `db:to_local` task and it's children tasks (specifically the `db:local_import` task)which seem to rely upon checking if a directory/file exists via the `local_file_exists?` method. I was expecting to find it in the `ash/common` file with the sibling `remote_file_exists` method but didn't find it there or in the rest of the `ash/base`.

**Comment by petemcw** [comment]
This issue was fixed with commit dc1afd7e08148b03e7ba2ca6b0785262ebac137c
