### ISSUE TITLE
cannot combine ash/hosted_magento with capistrano-multiconfig

### ISSUE THREAD

**Issue by arthos** [augustash/capistrano-ash#20]
recipes: https://github.com/railsware/capistrano-multiconfig + https://github.com/augustash/capistrano-ash/wiki/Shared-Hosting-Magento-Example

I try to deploy a magento shop to different servers.
The only difference is a theme in an other language and the database.
The codebase is the same.
I want to deploy something like:
![tree](http://s1.directupload.net/images/120328/eggsfmby.png)

but if i issue:
$ cap -T 
the task `staging' does not exist

can you give me a hint how to solve this ?

Greets and thnx :)

**Comment by grafikchaos** [comment]
I personally haven't used the capistrano-multiconfig before but one of our developers has done a capistrano/capistrano-multiconfig deployment before (without using our capistrano-ash recipes). I'll ask him to comment on this.

The `staging` task is available with the [capistrano-ext gem](https://github.com/jamis/capistrano-ext) and essentially uses the desired environment's ruby deploy file (in this case 'staging.rb'), but you could have numerous environments you can deploy to. For example you could have a demo or quality environments with correspond `demo.rb` and `quality.rb` deploy files.

You may also want to look more into the documentation on [Capistrano roles](https://github.com/capistrano/capistrano/wiki/Roles) as you can deploy your codebase to multiple servers that have different purposes (web, app, db). That's where the beauty and power of Capistrano really shines.

**Comment by arthos** [comment]
what a shame that i didnt try to create different [stage].rb ... now i can deploy the multilanguage shop to different servers.
thnx mate :)
