### ISSUE TITLE
change owner ship of directories/files in `deploy:cleanup` to avoid permission denied errors

### ISSUE THREAD

**Issue by JeffCost** [augustash/capistrano-ash#30]
Drupal shared server deployments are still having issues with removing old releases giving a `Permission Denied` error when trying to remove anything in the `sites` directories

``` ruby
namespace :deploy do

  #... blah blah blah
  namespace :cleanup do
    # ... blah blah blah
    directories.split(" ").each do |dir|
      # adding a chown -R method to fix permissions on the little jerk
      try_sudo "chown -R #{user}:#{user} #{dir}"

      set_perms_dirs(dir)
      set_perms_files(dir)
    end
  end
end
```

**Comment by dficker** [comment]
I've seen the issue you Jefferson describes but haven't been able to figure out why it happens in a few isolated instances but not others.  It seems that maybe when the deployment does not complete (or get to a certain point) this problem happens?
