### ISSUE TITLE
Add default branches to "staging" and "production"?

### ISSUE THREAD

**Issue by dficker** [augustash/capistrano-ash#31]
Right now, any deploy using Git goes from the confusing "HEAD".  It seems it should either be included in the Wiki documentation that you should set a branch (well, for that matter, to include some Git documentation in the Wiki at all), or even better, to provide "develop" and "master" as default branches for each environment.

**Comment by grafikchaos** [comment]
hmmm...I agree with updating the WIKI docs to show git examples but I don't know about automating/hijacking the `capify` command to create `config/deploy/<environment>.rb` files

**Comment by grafikchaos** [comment]
updated the WIKI pages to provide examples for github repositories and defining which branches to use when doing a multi-stage (environment) project"
