### ISSUE TITLE
Port issues with compass

### ISSUE THREAD

**Issue by americkson** [augustash/capistrano-ash#43]
Here is the error:
/Users/dev/.rbenv/versions/1.9.3-p448/lib/ruby/gems/1.9.1/gems/capistrano-2.15.5/lib/capistrano/configuration/namespaces.rb:193:in `method_missing': undefined local variable or method`port' for #Capistrano::Configuration::Namespaces::Namespace:0x000001009e8468 (NameError)

**Comment by grafikchaos** [comment]
Released new capistrano-ash version [1.3.4](http://rubygems.org/gems/capistrano-ash)

``` bash
$ gem install capistrano-ash
```
