### ISSUE TITLE
Magento deployment ignores ':use_sudo' for some operations

### ISSUE THREAD

**Issue by bverhoeven** [augustash/capistrano-ash#45]
Even when you set `:use_sudo` to false, certain operations will still require sudo to run, for example rsync'ing the media folder during `finalize_update`.

This is caused by the use of `sudo` instead of `try_sudo`. A fix should therefore be trivial.

**Comment by grafikchaos** [comment]
Released new capistrano-ash version [1.3.4](http://rubygems.org/gems/capistrano-ash)

``` bash
$ gem install capistrano-ash
```
